name: Compilation
# Whenever a release is published, the document gets compiled and added to the release.

on:
  release:
    types: [ published  ]

jobs:
  compile_upload_asset:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: ./.github/actions/compile
        with:
          root_file: main-german.tex
      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: main-german.pdf
          asset_name: Bachelorarbeit_Axel_Herrmann_Woche_final.pdf
