name: Compilation
# Whenever a release is published, the document gets compiled and added to the release.

on:
  release:
    types: [ published  ]

jobs:
  compile_upload_asset:
    uses: ./.github/workflows/compile_upload_asset.yml
    with:
      upload-url: ${{ github.event.release.upload_url }}
    permissions:
      contents: write
