name: Continuous Release

on:
  schedule:
    - cron: '30 22 * * SUN' # Run every sunday at 23:59 (+2 Berlin)

env:
  PDF_NAME: Bachelorarbeit_Axel_Herrmann_Woche_${{ github.run_number }}.pdf

jobs:
  create-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      upload-url: ${{ steps.output-upload-url.outputs.upload-url }}
      pdf-name: ${{ steps.output-pdf-name.outputs.pdf-name }}
    steps:
      - uses: actions/checkout@v3
      - name: Publish Release
        id: publish_release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          name: Week ${{ github.run_number }}
          tag_name: week_${{ github.run_number }}
      - name: Compile LaTeX document
        uses: ./.github/actions/compile
        with:
          root_file: main-german.tex
      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.publish_release.outputs.upload_url }}
          asset_path: main-german.pdf
          asset_name: ${{ env.PDF_NAME }}
