name: Continuous Release

on:
  schedule:
    - cron: '30 21 * * SUN' # Run every sunday at 23:59 (+2 Berlin)

env:
  PDF_NAME: Bachelorarbeit_Axel_Herrmann_Woche_${{ github.run_number }}.pdf

jobs:
  create-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      upload-url: ${{ steps.output-upload-url.outputs.upload-url }}
      pdf-name: ${{ steps.output-pdf-name.outputs.pdf-name }}
    steps:
      - name: Publish Release
        id: publish_release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          name: Week ${{ github.run_number }}
          tag_name: week_${{ github.run_number }}
      - name: Output upload URL
        id: output-upload-url
        run: echo "upload-url=${{ steps.publish_release.outputs.upload_url }}" >> $GITHUB_OUTPUT
      # Workourand for a bug where env is not available in the second job, similar to: https://github.com/actions/runner/issues/1189
      - name: Output PDF_NAME
        id: output-pdf-name
        run: echo "pdf-name=${{ env.PDF_NAME }}" >> $GITHUB_OUTPUT

  compile_upload_asset:
    uses: ./.github/workflows/compile_upload_asset.yml
    needs: create-release
    with:
      upload-url: ${{ needs.create-release.outputs.upload-url }}
      asset-name: ${{ needs.create-release.outputs.pdf-name }}
    permissions:
      contents: write
